CRcollector_project/CRcollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

CRcollector_project/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cards/', views.cards_index, name='index'),
    path('cards/<int:card_id>/', views.cards_detail, name='details'),
    path('cards/create/', views.CardCreate.as_view(), name='card_create'),
    path('cards/<int:pk>/update/', views.CardUpdate.as_view(), name="cards_update"),
    path('cards/<int:pk>/delete/', views.CardDelete.as_view(), name='cards_delete'),

    path('cards/<int:pk>/add_status/', views.add_status, name='add_status'),
    path('cards/<int:pk>/assoc_player/<int:player_pk>/', views.assoc_player, name='assoc_player'),
    path('cards/<int:pk>/assoc_delete/<int:player_pk>', views.assoc_delete, name='assoc_delete'),


    #Player URLS
    path('players/', views.PlayerList.as_view(), name='players_index'),
    path('players/<int:pk>/', views.PlayerDetail.as_view(), name='players_detail'),
    path('players/create/', views.PlayerCreate.as_view(), name="players_create"),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='player_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='player_delete'),
]

CRcollector_project/main_app/models.py
from django.db import models
from django.urls import reverse



STATUS = (
    ('1', 'LEVEL 1'),
    ('2', 'LEVEL 2'),
    ('3', 'LEVEL 3'),
    ('4', 'LEVEL 4'),
    ('5', 'LEVEL 5'),
    ('6', 'LEVEL 6'),
    ('7', 'LEVEL 7'),
    ('8', 'LEVEL 8'),
    ('9', 'LEVEL 9'),
    ('10', 'LEVEL 10'),
    ('11', 'LEVEL 11'),
    ('12', 'LEVEL 12'),
    ('13', 'LEVEL 13'),
    ('14', 'LEVEL 14'),
)

class Player(models.Model):
    player_name = models.CharField(max_length=100)

    def __str__(self):
        return self.player_name
    
    def get_absolute_url(self):
        return reverse('players_detail', kwargs={'pk': self.id})
    
# Create your models here.
class Card(models.Model):
    name = models.CharField(max_length=100)
    rarity = models.CharField(max_length=100)
    cost = models.IntegerField()
    players = models.ManyToManyField(Player)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('details', kwargs={'card_id': self.id})
    
class Status(models.Model):
    date = models.DateField('Upgraded on(example: 2024-05-12)') #Was unsure of adding a placeholder text. 
    status = models.CharField(max_length=14, choices=STATUS, default=STATUS[0][0])
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_status_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

    

CRcollector_project/main_app/forms.py
from django.forms import ModelForm
from .models import Status

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['date','status']

CRcollector_project/main_app/views.py
from django.shortcuts import render, redirect
from .models import Card, Player
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import StatusForm
from django.views.generic import ListView, DetailView


# cards = [
#     {'name':'Hog Rider', 'level': '5', 'rarity': 'rare', 'cost': 4}, 
#     {'name':'Witch', 'level': '12', 'rarity': 'epic', 'cost': 5}, 
#     {'name':'Mini P.E.K.K.A', 'level': '14', 'rarity': 'rare', 'cost': 4},
# ]

# Create your views here.
def home(request):
    return render(request, 'cr/home.html')

def about(request):
    return render(request, 'cr/about.html')

def cards_index(request):
    cards = Card.objects.all() # This is our get() method from our database for all cards. 
    return render(request, 'cr/index.html', {
        'cards': cards
    }) 

def cards_detail(request, card_id):
    card = Card.objects.get(id=card_id)
    players = Player
    id_list = card.players.all().values_list('id')
    buddies_card_is_not_assoc = Player.objects.exclude(id__in=id_list)
    status_form = StatusForm()
    return render(request, 'cr/detail.html', {'card':card, 'status_form': status_form, 'players': buddies_card_is_not_assoc})

def add_status(request, pk):
    form = StatusForm(request.POST)
    if form.is_valid():
        new_status = form.save(commit=False)
        new_status.card_id = pk
        new_status.save()
    return redirect('details', card_id=pk)

def assoc_player(request, pk, player_pk):
    Card.objects.get(id=pk).players.add(player_pk)
    return redirect('details', card_id=pk)

def assoc_delete(request, pk, player_pk):
    Card.objects.get(id=pk).players.remove(player_pk)
    return redirect('details', card_id=pk)

class CardCreate(CreateView):
    model = Card
    fields = ['name','rarity','cost']

class CardUpdate(UpdateView):
    model = Card
    fields = ['name','rarity','cost']

class CardDelete(DeleteView):
    model = Card
    success_url = '/cards/'

class PlayerList(ListView):
    model = Player

class PlayerDetail(DetailView):
    model = Player

class PlayerCreate(CreateView):
    model = Player
    fields = '__all__'

class PlayerUpdate(UpdateView):
    model = Player
    fields = ('player_name', )

class PlayerDelete(DeleteView):
    model = Player
    success_url = '/players'

CRcollector_project/main_app/templates/cr/about.html
{% extends 'cr/home.html' %}
{% block content %}
<div class="text-center">
<h1>About</h1>
<p>Welcome to the Clash Royale Collection application where users can upload their own Clash Royale cards to share with other Clash Royale players. Currently under production.</p>    
</div>

{% endblock %}

CRcollector_project/main_app/templates/cr/detail.html
{% extends 'cr/home.html' %}
{% block content %}
<div class="container">
<h1>{{card.name}} Details</h1>

<hr>
    <div>
        <div>
            <h3><span>{{ card.name }}</span></h3>
            <p>Rarity: {{ card.rarity }}</p>
            {% if card.cost > 0 %}
                <p>Elixir Cost: {{ card.cost }}</p>
            {% else %}
                <p>Elixir Cost: Free</p>
            {% endif %}
            <div>
                <a class="btn btn-success btn-sm" href="{% url 'cards_update' card.id %}">EDIT</a>
                <a class="btn btn-danger btn-sm" href="{% url 'cards_delete' card.id %}">DELETE</a>
            </div>
        </div>
    </div>
<div class="text-end">
    <form action="{% url 'add_status' card.id %}" method="POST">
        {% csrf_token %}
        {{ status_form.as_p }}
        <input class="btn btn-success btn-sm" type="submit" value="Add Level"/>
    </form>    
<!-- This is the Markup for showing the cards' statuses.  -->
    <h3 class="text-center">Level Status</h3>
    <table class="table table-striped">
        <thread>
            <tr><th>Date</th><th>Level</th></tr>
        </thread>
        <tbody>
            {% for status in card.status_set.all %}
            <tr>
                <td>{{status.date}}</td>
                <td>{{status.get_status_display}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
    <hr>
    <!-- Removal and Adding Existing Players -->
    <div class="d-inline p-5">
        <div class="row">
            <div class="col">
                <h3>{{ card.name }}'s Players</h3>
                {% if card.players.count %}
                    {% for player in card.players.all %}
                        <div class="d-inline-block mr-3">
                            <h3>{{ player.player_name }}</h3>
                            <form class="d-inline" action="{% url 'assoc_delete' card.id player.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">REMOVE</button>
                            </form>
                        </div>
                    {% endfor %}
                {% else %}
                    <h4>No Gaming Buddies</h4>
                {% endif %}
            </div>
    
            <div class="col">
                <h3>Local Players</h3>
                {% if players.count %}
                    {% for player in players.all %}
                        <div class="d-inline-block mr-3">
                            <h3>{{ player.player_name }}</h3>
                            <form class="d-inline" action="{% url 'assoc_player' card.id player.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success btn-sm">ADD FRIEND</button>
                            </form>
                        </div>
                    {% endfor %}
                {% else %}
                    <h5>{{ card.name }} is Friends with Everyone!</h5>
                {% endif %}
            </div>
        </div>
    </div>
    
{% endblock %}

CRcollector_project/main_app/templates/cr/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ClashRoyaleCollection</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body justify-content-start p-3" data-bs-theme="dark">
        <li><a class="text-decoration-none" href="/">Home</a></li>
        <li><a class="text-decoration-none" href="{% url 'about' %}">About</a></li>
        <li><a class="text-decoration-none" href="{% url 'index' %}">All Cards</a></li>
        <li><a class="text-decoration-none" href="{% url 'players_index' %}">All Players</a></li>
        <li><a class="text-decoration-none" href="{% url 'card_create' %}">Make New Card</a></li>
        <li><a class="text-decoration-none" href="{% url 'players_create' %}">Make a New Player</a></li>
    </nav>
    <div class="mt-5 text-center">
        <h1>Clash Royale Collection</h1>
    </div>
    {% block content %}
    {% endblock %} 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

CRcollector_project/main_app/templates/cr/index.html
{% extends 'cr/home.html' %}
{% block content %}
<h1 class="text-center mt-5">Existing Cards</h1>
<div class="container">
    <div class="row">
        {% for card in cards %}
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">{{ card.name }}</h3>
                        <p class="card-text">Rarity: {{ card.rarity }}</p>
                        {% if card.cost > 0 %}
                            <p class="card-text">Elixir Cost: {{ card.cost }}</p>
                        {% else %}
                            <p class="card-text">Elixir Cost: Free</p>
                        {% endif %}
                        <a href="/cards/{{ card.id }}" class="btn btn-primary btn-sm">Learn More</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

CRcollector_project/main_app/templates/main_app/card_confirm_delete.html
{% extends 'cr/home.html' %}
{% block content %}

<div class="container">
    <h1>Delete Card</h1>

    <div class="card mb-4">
        <div class="card-body">
            <h4 class="card-title">Are you sure you want to delete <span class="text-danger">{{ object.name }}</span>?</h4>
            <form action="" method="POST" class="mt-4">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mr-2">Yes - Delete!</button>
                <a href="{% url 'details' card.id %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>


{% endblock %}

CRcollector_project/main_app/templates/main_app/card_form.html
{% extends 'cr/home.html' %}
{% block content %}
<div class="container">
    <div class="card p-4 shadow-sm">
        {% if object %}
            <h1 class="mb-4">Edit <span class="text-primary">{{ object.name }}</span></h1>
        {% else %}
            <h1 class="mb-4">Add Card</h1>
        {% endif %}

        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary btn-block py-2 rounded-pill">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

CRcollector_project/main_app/templates/main_app/player_confirm_delete.html
{% extends 'cr/home.html' %}

{% block content %}
<div class="container">
    <h1>Delete {{ object.player_name }}</h1>

    <div class="card mb-4">
        <div class="card-body">
            <h4 class="card-title">Are you sure you want to delete <em>{{ object.player_name }}?</em></h4>
            <form action="" method="POST" class="mt-4">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mr-2">Yes - Delete!</button>
                <a href="{% url 'players_detail' object.id %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

CRcollector_project/main_app/templates/main_app/player_detail.html
{% extends 'cr/home.html' %}
{% block content %}

<div class="container">
    <h1>Player Details</h1>

    <div class="card mb-4">
        <div class="card-body">
            <h3 class="card-title">{{ player.player_name }}</h3>
            <p class="card-text">
                Hi, my name is {{ player.player_name }} and I have been playing for 5 years and would love to become your gaming buddy!
            </p>
            <div class="mt-3">
                <a href="{% url 'player_update' player.id %}" class="btn btn-primary mr-2">EDIT</a>
                <a href="{% url 'player_delete' player.id %}" class="btn btn-danger">DELETE</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

CRcollector_project/main_app/templates/main_app/player_form.html
{% extends 'cr/home.html' %}
{% block content %}

<div class="container">
    {% if object %}
        <h1 class="mb-4">EDIT Player Info</h1>
    {% else %}
        <h1 class="mb-3">Add Player Friend</h1>
        <p class="mb-4">This is where you can make players aka "Gaming Buddies" for your existing C.R. cards.</p>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        <div class="card p-4 shadow-sm">
            <div class="mb-3">
                {{ form.as_p }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary py-2 px-4 rounded-pill btn-sm">Submit</button>
    </form>
</div>


{% endblock %}

CRcollector_project/main_app/templates/main_app/player_list.html
{% extends 'cr/home.html' %}
{% block content %}

<div class="container">
    <h1>Players List</h1>

    <div class="row">
        <div class="col">
            <h3>Potential Gaming Buddies:</h3>

            <div class="card">
                <div class="card-body">
                    {% for player in player_list %}
                        <a href="{% url 'players_detail' player.id %}" class="text-decoration-none">
                            <h5 class="card-title">{{ player.player_name }}</h5>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}